/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_CoffeeCatchDemo_native_lib */

#ifndef _Included_com_example_CoffeeCatchDemo_native_lib
#define _Included_com_example_CoffeeCatchDemo_native_lib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_CoffeeCatchDemo_native_lib
 * Method:    native_func
 * Signature: (F)I
 */
JNIEXPORT jint JNICALL Java_com_example_CoffeeCatchDemo_native_1lib_native_1func
  (JNIEnv *, jobject, jfloat);
#ifdef __cplusplus
}
#endif
#endif


